inventario/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^login$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout$', logout, {'next_page': 'login'}, name='logout'),
    url(r'personas/', include('personas.urls', namespace='personas')),
    url(r'recursos/', include('recursos.urls', namespace='recursos')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personas/urls.py
from django.conf.urls import url, include
from personas.views import PersonCreateView, PersonListView, PersonUpdateView, PersonDetailView

urlpatterns = [
    url(r'^registro$', PersonCreateView.as_view(), name='create-person'),
    url(r'^lista$', PersonListView.as_view(), name='list-person'),
    url(r'^(?P<id>[-\w]+)/update/$', PersonUpdateView.as_view(), name='update-person'),
    url(r'^(?P<id>[-\w]+)/$', PersonDetailView.as_view(), name='detail-person'),

]

recursos/urls.py
from django.conf.urls import url, include
from recursos.views import *

urlpatterns = [
    url(r'^registro/inventario$', RecursoCreateView.as_view(), name='create-recurso'),
    url(r'^lista/inventario$', RecursoListView.as_view(), name='list-recurso'),
    url(r'^(?P<id>[-\w]+)/update/$', RecursoUpdateView.as_view(), name='update-recurso'),
]

personas/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from recursos.models import Recurso


class Persona(User):
    identificacion = models.CharField(blank=True, max_length=100, verbose_name='Identificación')
    recursos = models.ManyToManyField(Recurso, blank=True)

recursos/models.py
from django.db import models

# Create your models here.
class Recurso(models.Model):
    nombre = models.CharField(max_length=45)
    categoria = models.CharField(max_length=45, blank=True, null=True)
    codigo = models.CharField(blank=True, max_length=45)
    marca = models.CharField(blank=True, max_length=45)
    serie = models.CharField(blank=True, max_length=45)
    def __str__(self):
        return str(self.nombre)

personas/forms.py
from django import forms
from django.forms import ModelForm
from personas.models import Persona
from recursos.models import Recurso

class PersonaForm(ModelForm):
    class Meta:
        model = Persona
        exclude=['is_active', 'last_login', 'groups', 'user_permissions', 'is_staff', 'date_joined', 'is_superuser','password1', 'password2', 'password', 'address', 'address_city',
             'phone', 'other_phone', 'profession', 'username']

        fields = ['first_name', 'last_name', 'identificacion']

        labels = {
            'first_name': 'Nombres',
            'last_name': 'Apellidos'
        }

class PersonaUpdateForm(ModelForm):
    recursos =forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=Recurso.objects.all(), required=True)
    class Meta:
        model = Persona
        fields = ['recursos']

recursos/forms.py
from django import forms
from django.forms import ModelForm
from recursos.models import Recurso


class RecursoForm(ModelForm):
    class Meta:
        model = Recurso
        fields =[
        'nombre',
        'categoria',
        'codigo',
        'marca',
        'serie',
        ]

personas/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from personas.models import Persona
from personas.forms import PersonaForm, PersonaUpdateForm
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView


class PersonCreateView(CreateView):
    model = Persona
    form_class = PersonaForm
    template_name ='personas/registro_persona.html'
    success_url = reverse_lazy('personas:list-person')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.first_name
        form.save()
        return super(PersonCreateView, self).form_valid(form)

class PersonListView(ListView):
    model = Persona
    template_name = 'personas/lista_personas.html'
    paginate_by = 10
    context_object_name = 'personas'

    def get_queryset(self):
        qs = Persona.objects.all()
        return qs

class PersonUpdateView(UpdateView):
    model = Persona
    form_class= PersonaUpdateForm
    template_name = 'personas/asignacion.html'
    success_url = reverse_lazy('personas:list-person')

    def get_object(self, queryset=None):
        obj = Persona.objects.get(pk=self.kwargs['id'])
        return obj

class PersonDetailView(DetailView):
    model = Persona
    template_name = 'recursos/lista_recursos.html'

    def get_object(self, queryset=None):
        obj = Persona.objects.get(pk=self.kwargs['id'])
        return obj

    def get_context_data(self, **kwargs):
        context = super(PersonDetailView, self).get_context_data(**kwargs)
        person = Persona.objects.get(id=self.kwargs['id'])
        recursos = person.recursos.all() if person.recursos else None
        is_detail = True
        context['recursos'] = recursos
        context['person'] = person
        context['is_detail'] = is_detail
        return context

recursos/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from recursos.models import Recurso
from recursos.forms import RecursoForm
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

# Create your views here.
class RecursoCreateView(CreateView):
    model=Recurso
    form_class = RecursoForm
    template_name = 'recursos/registro_recurso.html'
    success_url = reverse_lazy('recursos:list-recurso')


class RecursoListView(ListView):
    model = Recurso
    template_name = 'recursos/lista_recursos.html'
    paginate_by = 10
    context_object_name = 'recursos'

    def get_queryset(self):
        qs = Recurso.objects.all()
        return qs


class RecursoUpdateView(UpdateView):
    model = Recurso
    form_class= RecursoForm
    template_name = 'recursos/registro_recurso.html'
    success_url = reverse_lazy('recursos:list-recurso')

    def get_object(self, queryset=None):
        obj = Recurso.objects.get(pk=self.kwargs['id'])
        return obj

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Inventario{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static  "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static "css/metisMenu.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head %}
    {% endblock %}

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Gestión de Inventario</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url 'logout'%}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#"><i class="fa fa-users"></i> Personas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'personas:create-person'%}"><i class="fa fa-table fa-fw"></i> Registro</a>
                                </li>
                                <li>
                                    <a href="{% url 'personas:list-person'%}"><i class="fa fa-th-list  "></i> Lista</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i>Recursos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'recursos:create-recurso' %}"><i class="fa fa-edit fa-fw"></i> Registro</a>
                                </li>
                                <li>
                                    <a href="{% url 'recursos:list-recurso' %}"><i class="fa fa-th-list"></i> Lista</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        {% block content %}
                        {% endblock %}
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static "/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static "js/metisMenu.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/sb-admin-2.js" %}"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Bienvenidos</h1>

{% endblock %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static  "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static "css/metisMenu.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                      <form class="form-signin m-t" role="form" method="post">
                             {% csrf_token %}
                             <h2 class="form-signin-heading">Inicia sesi&oacute;n</h2>
                             <div class="form-group">
                                 <input class="form-control" id="inputEmail" type="text" name="username" placeholder="Correo" >
                                 <input class="form-control" id="inputPass" type="password" name="password" placeholder="Contrase&ntilde;a" >
                             </div>
                             <button type="submit" class="btn btn-primary btn-lg btn-block full-width m-b"><i class="fa fa-sign-in"></i>&nbsp;Inicia sesi&oacute;n</button>
                         </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="{% static "/jquery/jquery.min.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static "js/metisMenu.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/sb-admin-2.js" %}"></script>

</body>

</html>

templates/personas/asignacion.html
{% extends "base.html" %}
{% load bootstrap_tags %}

{% block content %}
{% if is_detail %}


{% else %}
<h2>Asignar Recursos</h2>
  <form action="" method="post">
      {% csrf_token %}
      {{ form|as_bootstrap }}
      <div class="form-actions">
        <a href="{% url 'index' %}" class="btn">Regresar</a>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
  </form>
{% endif %}
{% endblock content %}

templates/personas/persona_list.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        Personas
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Recursos</th>
                    </tr>
                </thead>
                <tbody>
                  {% for p in personas %}
                    <tr>
                        <td>{{p.id}}</td>
                        <td>{{p.first_name}}</td>
                        <td>{{p.last_name}}</td>
                        <td><a class="btn btn-outline btn-primary" href="{% url 'personas:detail-person' p.id%}"> Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

{% endblock %}

templates/personas/registro_persona.html
{% extends "base.html" %}
{% load bootstrap_tags %}

{% block content %}
<h2>Registro personas</h2>
  <form action="" method="post">
      {% csrf_token %}
      {{ form|as_bootstrap }}
      <div class="form-actions">
        <a href="{% url 'index' %}" class="btn">Regresar</a>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
  </form>
{% endblock content %}

templates/recursos/lista_recursos.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="panel panel-default">
    <div class="panel-heading">
      {% if is_detail %}
          Recursos Asignados a <strong>{{person.first_name}}</strong>
          <a class="btn btn-primary" href="{% url 'personas:update-person' person.id %}"><i class="fa fa-plus"></i></a>
        {% else %}
        Recursos
      {% endif %}
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Categoria</th>
                        <th>Codigo</th>
                        <th>Serie</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                  {% for p in recursos %}
                    <tr>
                      <td>{{p.id}}</td>
                        <td>{{p.nombre}}</td>
                        <td>{{p.categoria}}</td>
                        <td>{{p.codigo}}</td>
                        <td>{{p.serie}}</td>
                        <td><a href="{% url 'recursos:update-recurso' p.id %}"><i class="fa fa-edit"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>
{% endblock %}

templates/recursos/registro_recurso.html
{% extends "base.html" %}
{% load bootstrap_tags %}

{% block content %}
<h2>Registro de Recursos</h2>
  <form action="" method="post">
      {% csrf_token %}
      {{ form|as_bootstrap }}
      <div class="form-actions">
        <a href="{% url 'index' %}" class="btn">Regresar</a>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
  </form>
{% endblock content %}